#!/bin/bash
# set -ex

repos="template"
repos+=" architettura-degli-elaboratori logica-per-informatica programmazione"
repos+=" algebra-e-geometria algoritmi-e-strutture-di-dati analisi-matematica"
repos+=" calcolo-numerico ottimizzazione-combinatoria"
repos+=" calcolo-delle-probabilita-e-statistica tecnologie-web"
repos+=" linguaggi-di-programmazione reti-di-calcolatori sistemi-operativi"
repos+=" basi-di-dati fisica laboratorio-di-applicazioni-mobili"
repos+=" storia-informatica-e-dei-dispositivi-di-calcolo strategia-aziendale"
repos+=" metodi-logici-per-la-filosofia laboratorio-sicurezza-informatica"
repos+=" ing-analisi-matematica-2-t ing-matematica-applicata-t"
repos+=" ing-fisica-generale-t ing-sistemi-operativi-t"
repos+=" ing-economia-e-organizzazione-aziendale-t"
repos+=" ing-laboratorio-amm-sistemi-t ing-fondamenti-di-telecomunicazioni-t"

root=$PWD
patch=$root/patch.diff

if [ -z "$1" ]; then
  echo "Usage: update <msg>"
  exit 1
fi

if [ ! -e $patch ]; then
  echo "$patch file not found. Create one with git diff"
  exit 1
fi

mkdir -p repos

for repo in $repos; do
  printf "== Patching %s\n" $repo

  dest="repos/$repo"
  if [ ! -d $dest ]; then
    printf "== Cloning %s\n" $repo
    git clone git@github.com:csunibo/$repo.git $dest
  fi

  printf "== Bringing %s up to date\n" $repo
  cd $dest
  git pull
  git reset --hard origin/main

  printf "== Patching %s\n" $repo
  patch -p1 < $patch
  git add .
  git commit -m "$1"


  printf "== Pushing %s\n" $repo
  git push

  cd $root
done
