#!/bin/bash
# set -ex

repos="template-it template-en "
repos+="$(jq -r '.[].url' < ./config/teachings.json)"

root=$PWD
patch=$root/patch.diff

if [ -z "$1" ]; then
  echo "Usage: update <msg>"
  exit 1
fi

if [ ! -e "$patch" ]; then
  echo "$patch file not found. Create one with git diff"
  exit 1
fi

mkdir -p repos

for repo in $repos; do
  printf "== Patching %s\n" "$repo"

  dest="repos/$repo"
  if [ ! -d "$dest" ]; then
    printf "== Cloning %s\n" "$repo"
    git clone --depth=1 "git@github.com:cartabinaria/$repo.git" "$dest"
  fi

  printf "== Bringing %s up to date\n" "$repo"
  cd "$dest" || exit 1
  git fetch --depth=1
  git reset --hard origin/main

  printf "== Patching %s\n" "$repo"
  patch -p1 < "$patch"
  git add .
  git commit -m "$1"


  printf "== Pushing %s\n" "$repo"
  git push

  cd "$root" || exit 1
done
